### PR TITLE
chore: Bump `bindgen` to `v0.70`

### PR DESCRIPTION
**Pull request by torokati44**
*knock-knock* Housekeeping!

### CODE REVIEW

**Review by Dinnerbone — APPROVED** [review]
Should we put the bot here?

**Comment by torokati44** [comment]
I thought about it, but this has so few dependencies, and they aren't updated (in a semver-incompatible way) that often, so there's barely any point to that IMHO.

**Comment by torokati44** [comment]
*grjfhdzatagejegshajaiasgsgezd*

But merge commits must be banned immediately. 😱🫠

**Comment by torokati44** [comment]
> But merge commits must be banned immediately. 😱🫠

Oh, I was able to force-push it away. ^^
EDIT: And also toggle that setting, yay!
Please excuse my clumsiness.

**Pull request merged**
